### ISSUE TITLE
Package targeting Nancy 1.x

### ISSUE THREAD

**Issue by jairov4** [Jaxelr/Nancy.Metadata.Swagger.Core#85]
Due to the documentation state backward compatibility, a package targeting Nancy 1.x would be nice. It would help many people to adopt this package meanwhile the migrate to 2.x

**Comment by Jaxelr** [comment]
Its doable, all i need to do is to target nancy 1.X if the target is not netstandard 2.0

**Comment by Jaxelr** [comment]
Just a heads up, i am publishing a prerelease myget a version that targets nancy 1.X on earlier builds. I also added a sample project for net fx 4.6.2 on the sample directory.

**Comment by Jaxelr** [comment]
Published on nuget release version 0.4.0
